### ISSUE TITLE
 linux-aarch64 missing in conda-forge

### ISSUE THREAD

**Issue by lrlunin** [PierreRaybaut/guiqwt#109]
Hello,

thank you very much for your software. I tried to install a 3d part library on my raspberry pi via conda and faced an issue that `guiqwt` could not be installed. Could I ask you to add `linux-aarch64` architecture for `conda-forge` distribution channel?

**Comment by PierreRaybaut** [comment]
Hello,

Thanks for using ``guiqwt`` (and trying to install it!).
I would be happy to help you but I'm not sure how I can answer your request because I'm not in charge of the distribution over ``conda-forge``.

Perhaps open the same issue here would help?
https://github.com/conda-forge/guiqwt-feedstock/issues

Please do not hesite to get back to me if you know how I can help you - again, I would be glad to do everything I can.

Pierre

**Comment by lrlunin** [comment]
resolved with https://github.com/conda-forge/guiqwt-feedstock/pull/35

**Comment by PierreRaybaut** [comment]
Great, thanks for taking care of it.
