### ISSUE TITLE
guiqwt try to frie my laptop :)

### ISSUE THREAD

**Issue by picca** [PierreRaybaut/guiqwt#14]
when building the doc, guiqwt use all my computer CPU load.

updating environment: 8 added, 0 changed, 0 removed
reading sources... [ 12%] development
reading sources... [ 25%] disthelpers
reading sources... [ 37%] examples
reading sources... [ 50%] index
reading sources... [ 62%] installation
reading sources... [ 75%] overview
reading sources... [ 87%] reference
Using experimental 'pure Python' qwt API

here...

I do not understand why but it takes minutes to get out of this

**Comment by PierreRaybaut** [comment]
This performance issue rings a bell... but I'm a lazy person (it takes a few second on my machines... so I'm simply waiting a little bit instead of trying to understand where it's coming from) :sweat_smile:
So, I will have to investigate further to see where it comes from.

**Comment by picca** [comment]
Lazy... hum it is time for you to learn haskell and never look back

**Comment by PierreRaybaut** [comment]
I still have no clue where this performance issue comes from. All that I know is that it happens when sphinx is compiling the reference documentation (documentation generated automatically using 'autodoc' extension): sphinx is probably importing all the modules, one after the other. However, it should not take so long to import all these modules. Perhaps there is some code snippet somewhere that is executed (some code that should be written after a "if __name__ == '__main__':" statement). I'll have to check that.

In the meantime, know that I have cleaned up all the docstrings and .rst files so that there is no more warnings showing up when building documentation.

**Comment by PierreRaybaut** [comment]
After having carefully checked the code, there's nothing to be done to avoid this CPU load during documentation generation. This is due to the `autodoc` Sphinx extension doing its work collecting docstrings in all guiqwt modules.
