### ISSUE TITLE
is 'PyTables' instead of 'h5py' possible in the tests?

### ISSUE THREAD

**Issue by stonebig** [PierreRaybaut/guiqwt#51]
hi Pierre,

Trying to do a Slim version of Winpython I discover that:
- 'pandas' relies on 'PyTables' for HDF stuff,
- 'guiqwt' relies on 'h5py'.

Is it an easy  change to shift to PyTables for the test `loadsaveitems_hdf5.py` ?

**Comment by PierreRaybaut** [comment]
I'm afraid not.

Besides, h5py seems to be a very basic library for HDF5 support. It is really complementary to PyTables.
________________________________
De : stonebig<mailto:notifications@github.com>
Envoyé : ‎10/‎11/‎2015 17:11
À : PierreRaybaut/guiqwt<mailto:guiqwt@noreply.github.com>
Objet : [guiqwt] is 'PyTables' instead of 'h5py' possible in the tests? (#51)

hi Pierre,

Trying to do a Slim version of Winpython I discover that:
- 'pandas' relies on 'PyTables' for HDF stuff,
- 'guiqwt' relies on 'h5py'.

Is it an easy  change to shift to PyTables for the test `loadsaveitems_hdf5.py` ?

---
Reply to this email directly or view it on GitHub:
https://github.com/PierreRaybaut/guiqwt/issues/51

**Comment by stonebig** [comment]
ok.
